excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://alva114.github.io
title: Card Data Recovery
tagline: Recover data from all types of Memory Card With Ease!!
description: Recover your lost or deleted data from all sortof Memory Card!
paginate: 5